os: linux
language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
cache:
  directories:
    - node_modules
before_install:
  - npm config set progress=true && npm i -g npm@latest --no-audit
install:
  - npm ci --no-audit
script:
  - npx jest
after_success:
  - npm run coveralls
