os: linux
dist: focal
language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm ci --no-audit

env:
  global:
  - COVERALLS_PARALLEL=true
  - COVERALLS_SERVICE_NAME="travis-ci"
script:
  - npm run lint
  - npm run test
  - npm run test:coveralls
  - npm run test:coverage

