os: linux
dist: focal
language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
cache:
  directories:
    - node_modules

env:
  global:
  - COVERALLS_PARALLEL=true
  - COVERALLS_SERVICE_NAME="travis-ci"
  - COVERALLS_REPO_TOKEN
script:
  - npm run lint
  - npm run test
  - npm run test:coveralls
  - npm run test:coverage

