os: linux
dist: focal
language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm ci --no-audit

env:
  global:
  - COVERALLS_PARALLEL=true
script:
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
after_success:
  - npm run coveralls
