os: linux
dist: focal
language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
cache:
  directories:
    - node_modules

jobs:
  include:
    -stage: test
      script:
        - npm run lint
        - npm run test
    -stage: coverage
      script:
        - npm run test:coverage
        - npm run upload-coverage

