language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npx jest
after_success:
  - npm run coveralls
