os: linux
dist: focal
language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
cache:
  directories:
    - node_modules

env:
  global:
  - COVERALLS_PARALLEL=true
#Issue confirming completion at Coveralls.io
script:
  - npm run lint
  - npm run test
  - npm run test:coverage
  - npm run upload-coverage

notifications:
  webhooks: https://coveralls.io/webhook