os: linux
dist: focal
language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
cache:
  directories:
    - node_modules

env:
  global:
    - COVERALLS_SERVICE_NAME="travis-ci"
    - COVERALLS_PARALLEL=true

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run test:coverage

after_success:
  - npm run upload-coverage

notifications:
  webhooks: https://coveralls.io/webhook

