os: linux
dist: focal
language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
cache:
  directories:
    - node_modules


script:
  - npm run lint
  - npm run test
  - npm run test:coverage
  - npm run upload-coverage

